### ISSUE TITLE
(MP) Punto 17: Ajustar remitente solamente. Cambiar remitente correo por: Plataforma Integridad. 

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#19]

**Comment by chapalele** [comment]
ajuste hecho en parámetros de la empresa...
![Screen Shot 2021-04-14 at 1 35 31 PM](https://user-images.githubusercontent.com/168235/114754996-2a116300-9d27-11eb-8615-9cee1be37283.png)
