### ISSUE TITLE
Cambiar color de botones de actividades en Integridad Ciudadana

### ISSUE THREAD

**Issue by karencossio** [chapalele/integridad-corporativa-issues#2]
En azul, utilizar paleta de colores del logo.

**Comment by chapalele** [comment]
cuáles son los colores de cada actividad?

**Comment by karencossio** [comment]
Se deben dejar todos en azul. es sólo para que destaquen a la vista

**Comment by karencossio** [comment]
Danilo, podemos tener esto listo hoy, publicado mañana? 
Lo vimos en la reunión del lunes ante pasado, porfa

**Comment by chapalele** [comment]
Sí, va a estar

**Comment by karencossio** [comment]
(Gracias, perdón lo hincha)
A propósito, el lunes podemos repasar cómo marcar lo de los plazos?

**Comment by chapalele** [comment]
publicado en https://stage.integridadciudadana.cl/

> (Gracias, perdón lo hincha)
> A propósito, el lunes podemos repasar cómo marcar lo de los plazos?

sip
