### ISSUE TITLE
Demo Stage: no se muestran categorías en escritorio de configuración

### ISSUE THREAD

**Issue by karencossio** [chapalele/integridad-corporativa-issues#24]
![image](https://user-images.githubusercontent.com/82000469/115097366-a9559100-9ef7-11eb-8e49-0da4961a7657.png)

La plataforma reconoce que existen categorías, pero no las muestra en interfaz que permite modificar las existentes o agregar nuevas

**Comment by chapalele** [comment]
@karencossio  ¿puedes confirmar si este bug sigue?
no puedo reproducir el problema en https://admin.stage.integridadcorporativa.cl/categoria/demo

![screencapture-admin-stage-integridadcorporativa-cl-categoria-demo-2021-04-20-05_58_43](https://user-images.githubusercontent.com/168235/115377335-86e4a180-a19d-11eb-8588-25268c19cc58.png)
