### ISSUE TITLE
(SB) 1. Al entrar como administrador, necesito poder agregar en todas las denuncias del año 2021, los siguientes parámetros, para que se vean reflejados en los gráficos: 1.1. Comuna. 1.2. Calidad de denunciante (colaborador, proveedor, cliente, etc.) 1.3. Empresa.

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#30]

**Comment by chapalele** [comment]
@AleToroY esto no lo puedo hacer, implica que el administrador puede adulterar los datos ingresados por el usuario.  Si quieres lo conversamos en una junta.

**Comment by karencossio** [comment]
Ale, conversamos este tema con Danilo. Conversaré con Constanza para explicar razones y alinear respuesta al cliente.

**Comment by AleToroY** [comment]
Ok, le avisaremos al cliente que no es factible esta solicitud.
