### ISSUE TITLE
(SB) 3. Al usar la plataforma como administrador, no puedo adjuntar archivos en las denuncias o consultas.

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#32]

**Comment by chapalele** [comment]
este comportamiento depende de un parámetro que puedes ajustar en la administración.
Lo activé en SB producción.

<img width="599" alt="Screen Shot 2021-04-22 at 5 42 49 AM" src="https://user-images.githubusercontent.com/168235/115693724-30f33380-a32e-11eb-997c-7464d502ac3f.png">
