### ISSUE TITLE
(SB) 4. En el panel de administración, no tengo visibilidad de las "declaraciones de proveedores". Ayer hice una de prueba y no pude revisarla como administrador.

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#33]

**Comment by chapalele** [comment]
@AleToroY ¿cuál es el usuario y el sitio?

**Comment by AleToroY** [comment]
Es de Empresas SB y es Jorge Valdivieso, Coordinador de Integridad.

**Comment by AleToroY** [comment]
Esto está pendiente.

**Comment by chapalele** [comment]
Normal, su perfil no tiene acceso a esos procedimientos, lo activé en producción.

<img width="1107" alt="Screen Shot 2021-04-30 at 7 04 00 AM" src="https://user-images.githubusercontent.com/168235/116687056-996f8f80-a982-11eb-9022-a7643fac4cc5.png">

<img width="1170" alt="Screen Shot 2021-04-30 at 7 04 57 AM" src="https://user-images.githubusercontent.com/168235/116687085-a0969d80-a982-11eb-80f2-629ba828d84d.png">
