### ISSUE TITLE
(SB) 5. Al hacer la declaración de proveedor y poner el último dato de los datos personales (número de teléfono), cuesta poner el botón "siguiente" y hay que hacer click en otro lado de la pantalla. Por favor, una vez que se rellenen los 3 item (nombre correo teléfono), que la posibilidad de poner siguiente sea automática.

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#34]

**Comment by chapalele** [comment]
Este tema lo hemos abordado antes, tiene que ver con el momento en que se hace la validación de los campos ingresados.

Como la validación se hace sobre un conjunto de campos variable (en el formulario de privacidad, pero sobre todo en el formulario de ingreso de información), hay que escoger un evento que lance la validación y que sea útil en todos los casos.  

En principio, las opciones son blur (al quitar el campo), change (al cambiar un valor) y keyup (al teclear cada letra) o una combinación de dos o los tres. (hay otros eventos relacionados con el ratón, pero no los incluyo aquí porque no nos sirven en dispositivos de pantalla táctil)

En el caso de integridad corporativa, la validación del formulario en pantalla se lanza con los dos primeros (blur y change).  Llegamos a esta opción principalmente por tres razones: 
1) cubre casi todos los casos de uso
2) si usamos keyup, veríamos los mensajes de error de validación desde el momento en que tecleas la primera letra y puede ser molesto llenar la pantalla de alertas antes de comenzar siquiera a escribir algo.
3) keyup ralentizaba el sistema en computadores viejos y nos daba problemas de compatibilidad con internet explorer.  Como es más intrusivo, puede hacer que moleste al escribir, que te saltes letras, etc.

Podríamos agregar keyup a la lista de eventos que lanza la validación, y con ello satisfacer el requisito, pero esa solución nos impone costos de usabilidad, sobre todo en computadores lentos que no estoy seguro de que queramos asumir, sobre todo, teniendo en cuenta que se trata de un cambio global, que afectaría a todas las plataformas.

Voy a dejar este ticket abierto para discutirlo en equipo, pero por el momento es un "wontfix"

**Comment by AleToroY** [comment]
Esto está pendiente.

**Comment by chapalele** [comment]
publicado en v6.2.30 (se mantiene en observación)
