### ISSUE TITLE
(SB) 6. Una vez que los proveedores hacen su declaración, la idea es que ellos no la puedan volver a modificar (porque de lo contrario, nunca tendría la certeza de que es lo que declararon). Entonces, preferiría que el acceso que tengan los proveedores que ya hicieron la declaración, solo sea para imprimir la declaración ya realizada y no puedan modificar nada. Sin perjuicio de eso, necesitamos que quede el registro para la administración.

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#35]

**Comment by chapalele** [comment]
@AleToroY  esto se nos está escapando de las manos... no podemos hacer un sistema completamente nuevo a golpe de modificaciones semanales que agregan funciones que no tienen nada que ver con el rol principal del sistema.  Por evidentes razones de costo y foco yo creo que este es un "wontfix".  Lo dejo abierto para discutir en equipo.

**Comment by chapalele** [comment]
cerrar el caso resuelve la solicitud (estado aprobado)

**Comment by AleToroY** [comment]
Ok, hablaremos con el cliente la posibilidad de cambiar el status y también la posibilidad de cambiar el nombre del botón si lo desea.
