### ISSUE TITLE
Crear stage bajo la dirección  quelenfruits.etica.integridadcorporativa.cl

### ISSUE THREAD

**Issue by karencossio** [chapalele/integridad-corporativa-issues#38]
Nueva empresa en implementación

**Comment by chapalele** [comment]
para ponerlo en stage debo guardar el subdominio, va a quedar en 

https://quelenfruits.stage.integridadcorporativa.cl

**Comment by chapalele** [comment]
https://quelenfruits.stage.integridadcorporativa.cl/

**Comment by karencossio** [comment]
Y el subdominio definitivo, puede incluir la palabra ética? como señala el cliente?

**Comment by chapalele** [comment]
@karencossio sí, en la plataforma en producción no hay problema, la restricción corre sólo para stage.

**Comment by karencossio** [comment]
perfecto, gracias!
