### ISSUE TITLE
(MP) cambiar orden botones flujo; primero consulta y luego denuncia (ahora están al revés) 

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#39]

**Comment by chapalele** [comment]
esto se puede ajustar en los parámetros de la empresa / procedimientos:

a mayor prioridad, más arriba aparece el botón.

ajusté el valor en stage para ministerio público.

<img width="634" alt="Screen Shot 2021-04-30 at 7 19 30 AM" src="https://user-images.githubusercontent.com/168235/116688391-a1303380-a984-11eb-8faf-d8171ad635ff.png">
