### ISSUE TITLE
Enviar propuesta a Ana María para manejar tema regiones

### ISSUE THREAD

**Issue by karencossio** [chapalele/integridad-corporativa-issues#4]

**Comment by chapalele** [comment]
enviado por correo:

> Hola Ana María,

En una de las reuniones de preparación del sitio de integridad corporativa para el Ministerio Público quedé con la tarea de estudiar cómo integrar en la administración de los datos la existencia de distintas fiscalías regionales.  En las siguientes líneas viene el resultado de este análisis.

Línea de base:

Los denunciantes pueden elegir una categoría para su expediente, en función de esa categoría se pueden implementar reglas para cambiar a) las preguntas del cuestionario y b) el(los) usuario(s) susceptibles de recibir el caso como responsable.

Los usuarios registrados que pueden recibir casos pertenecen a uno de dos tipos de perfiles:
1) perfil de administración: puede editar todos los casos del sistema
2) perfil de escritura: puede editar sólo los casos donde el usuario es responsable.

En ambos casos, los perfiles están limitados por la lista de categorías.  Esto es: cada perfil tiene acceso a una lista de categorías (editable).  Ningún caso perteneciente a una categoría fuera de esa lista es visible por parte del usuario inscrito en el perfil.

Como puedes ver, no hay en la línea de base la posibilidad de caracterizar o filtrar los casos por fiscalía, o dejar "oculto" un caso a un usuario basado en ese dato.

Propuestas:

a) hacer un sitio de integridad por cada fiscalía: esto permite que cada fiscalía pueda organizar sus recursos: (usuarios, perfiles, casos, categorías, etc,) en forma independiente y aislada.  Con esto se trata cada fiscalía como una empresa aparte, lo que no impide compartir recursos como categorías o formularios, pero sí impide que los casos viajen de una fiscalía a otra.

b) hacer un pequeño ajuste a la interfaz del sitio, para que al ingresar un caso, el denunciante vea la lista de posibles destinatarios acotada a los usuarios relevantes según la zona geográfica que él eligió al responder el cuestionario.  Sin embargo, este cambio no tiene ningún impacto sobre la accesibilidad de los casos en el backend: los perfiles con acceso de administración podrán ver y editar los casos de todas las fiscalías.

c) no hacer nada, y entregar indicaciones a los usuarios en la interfaz de ingreso de caso como comentario o mensaje de ayuda.

Quedo atento y disponible para que conversemos.

Saludos,

danilo
