### ISSUE TITLE
(MP) 4.	Una advertencia como la del MOP (copio ejemplo del MOP). Al apretar botones para ingresar una denuncia o una consulta. Les enviaría el texto a la brevedad. (ES UN POP-UP, TE MANDO FOTO POR WPP)

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#43]

**Comment by chapalele** [comment]
publicado en stage

<img width="917" alt="Screen Shot 2021-05-12 at 8 34 57 AM" src="https://user-images.githubusercontent.com/168235/117975765-0547e580-b2fd-11eb-9bf2-0aec2c323aa3.png">
