### ISSUE TITLE
(MP) Desde administración, 6.	De requerirse más adelante, ¿es posible agregar otras clasificaciones además de ingreso, en proceso y cerrado? De todas maneras, por el momento está ok.

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#45]

**Comment by chapalele** [comment]
esto es configurable en el sitio de administración de la empresa...

<img width="322" alt="Screen Shot 2021-04-29 at 6 10 08 AM" src="https://user-images.githubusercontent.com/168235/116535422-bbe5a800-a8b1-11eb-821b-403cd9efb5cf.png">
