### ISSUE TITLE
(MP) Ni en consulta ni en denuncia los consultantes/denunciantes pueden adjuntar archivos adicionales, cuando entran a la revisión del estado de su caso. 

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#49]

**Comment by chapalele** [comment]
esto se controla en los parámetros de la empresa
<img width="539" alt="Screen Shot 2021-04-28 at 11 48 54 PM" src="https://user-images.githubusercontent.com/168235/116500744-321be780-a87d-11eb-9aa2-f82564f63748.png">
