### ISSUE TITLE
(MP) Otra cosa que observé a propósito del comportamiento, hasta ahí supuesto de los responsables, pero que ahora veo que es de sistema, es que si como responsable (perfil escritura) aprieto cambiar responsable, aunque no elija a nadie y sólo sea para ver las opciones que aparecen, por defecto cambia y deja al primero de la lista sin advertirse (de hecho, en la lista no se encuentra el mismo responsable). Eso no pasa desde los coordinadores o perfil administración pues aparece por defecto el responsable actual dentro de la lista.

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#51]

**Comment by chapalele** [comment]
cerrado con v6.2.33

**Comment by chapalele** [comment]
solución:
fundir con 6.3 (carga ajax de usuarios y categorías)

**Comment by AleToroY** [comment]
Hola Danilo, Ana nos volvío a escribir sobre este tema, te dejo lo que puso ahora, solamente por si te entrega información adicional que te ayude a resolverlo: 8.	Sigue problema respecto del cambio automático de responsable; lo cambia al entrar y grabar desde un perfil de responsable (escritura); ni siquiera es necesario apretar cambiar responsable, ni agregar nuevo antecedente; sólo con grabar cambia el responsable (a Coordinador 1 Diego para casos no MALS y a Alejandra para casos MALS, ambos los primeros en la lista desplegable). No pasa lo mismo cuando uno entra y graba desde administración, ahí no hace ese tipo de cambio. Esto hay que resolverlo ya. No puedo seguir haciendo pruebas con este error y se hace evidente para el cliente, pues le llegan correos y a los responsables les desaparece el caso de sus grillas. En el impacto real, no puede ocurrir que alguien reciba un caso que no va dirigido o no ha sido asignado a esa persona.

**Comment by chapalele** [comment]
corregido en v 6.3.1
