### ISSUE TITLE
(ABCDin) Desde hace ya algunos meses que no me han llegado correos de notificación del Canal de Denuncias cuando se ingresa una denuncia/consulta o con cualquier otra actividad. La verdad es que no me había llamado la atención porque asumí que simplemente no había llegado nada, pero hoy entré a revisar más a profundidad y habían varios casos nuevos que no se me notificaron, así como tampoco las gestiones que hice hoy. Acá revisé si se me estaban yendo a correo no deseado o spam y nada. Favor revisar esa situación."

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#52]

**Comment by chapalele** [comment]
Hola Coni, gracias por escribir.

Tengo montones de notificaciones entregadas a José Castillo. Salvo si hay un error en la dirección de correo (no creo) no veo ninguna razón atribuible a nosotros para que los correos no lleguen.

Los mensajes fueron entregados al servidor de adretail y no hay evidencia de problemas al menos de nuestro lado.

Aquí van capturas de pantalla de una lista de entregas y el texto de una de las confirmaciones...

{"notificationType":"Delivery","mail":{"timestamp":"2021-04-14T00:34:52.996Z","source":"Integridad Corporativa <integridad@gsocial.cl>","sourceArn":"arn:aws:ses:us-east-1:518874808975:identity/integridad@gsocial.cl","sourceIp":"54.161.226.209","sendingAccountId":"518874808975","messageId":"01000178cdcd63c4-5699cea8-cb7e-4d22-8247-3eefa74df239-000000","destination":["\"Gonzalo Ceballos\" <gonzalo.ceballos@abcdin.cl>","\"José Castillo\" <Jose.Castillo@adretail.cl>"],"headersTruncated":false,"headers":[{"name":"Return-Path","value":"integridad@gsocial.cl"},{"name":"From","value":"Integridad Corporativa <integridad@gsocial.cl>"},{"name":"Reply-To","value":"integridad@gsocial.cl"},{"name":"To","value":"\"Josï¿½ Castillo\" <Jose.Castillo@adretail.cl>,  Gonzalo Ceballos <gonzalo.ceballos@abcdin.cl>"},{"name":"Subject","value":"Nueva denuncia en Integridad corporativa"},{"name":"MIME-Version","value":"1.0"},{"name":"Content-Type","value":"multipart/alternative;  boundary=\"----=_Part_861835_600153497.1618360493000\""}],"commonHeaders":{"returnPath":"integridad@gsocial.cl","from":["Integridad Corporativa <integridad@gsocial.cl>"],"replyTo":["integridad@gsocial.cl"],"to":["\"Josï¿½ Castillo\" <Jose.Castillo@adretail.cl>","Gonzalo Ceballos <gonzalo.ceballos@abcdin.cl>"],"subject":"Nueva denuncia en Integridad corporativa"}},"delivery":{"timestamp":"2021-04-14T00:34:56.214Z","processingTimeMillis":3218,"recipients":["gonzalo.ceballos@abcdin.cl"],"smtpResponse":"250 ok:  Message 25502154 accepted","remoteMtaIp":"139.138.57.189","reportingMTA":"a48-180.smtp-out.amazonses.com"}}

Screen Shot 2021-04-29 at 5.45.02 AM.png

Importante antecedente:

En ADRetail teníamos unas cuentas que rebotaban y yo les pedí a ustedes (gestión social) que las gestionaran, dando de baja los usuarios o corrigiendo los correos).  Es posible que el servidor de correo de adretail completó la cuota de errores y nos bloquea los correos automáticamente.  En cualquier caso y por el momento, la solución del problema está por el lado de ellos.

saludos

danilo
