### ISSUE TITLE
(MP) Otra duda vemos que los coordinadores, por ejemplo, que tienen perfil administración, pueden intervenir los expedientes, aunque no sean los responsables (a quien se les asignó el caso), ¿es posible identificar, aunque sea internamente, quién hizo qué?, pues en la bitácora sólo dice "la persona a cargo

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#53]

**Comment by chapalele** [comment]
Sí, ese es un parámetro que puede cambiarse en la configuración de la empresa:
Con todo, la información queda en la base de datos, aunque no sea visible, por ejemplo, para investigaciones posteriores.

<img width="610" alt="Screen Shot 2021-04-30 at 6 51 20 AM" src="https://user-images.githubusercontent.com/168235/116685638-af7c5080-a980-11eb-98dd-841ee894710d.png">
