### ISSUE TITLE
(SB) persistencia de la tabla administración. 

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#56]

**Comment by chapalele** [comment]
@AleToroY  ¿qué es esto?

**Comment by AleToroY** [comment]
Cuando uno está en la parte de administración y ordena la tabla de las denuncias, luego cuando vuelve a entrar el orden que uno puso no se quedó (se resetea), le gustaría a la contraparte que el orden que pusó se quede para cuando vuelva a entrar.

**Comment by chapalele** [comment]
> @AleToroY ¿en qué versión, empresa, perfil? está el problema 

olvídalo, es SB: stage y producción

**Comment by AleToroY** [comment]
En Empresas SB, en la versión en producción, perfil coordinador general.

**Comment by AleToroY** [comment]
Jorge (cliente) solicita el siguiente orden: Nombre / categoría / fecha creación / acciones. Y que se ordene de fecha de creación más reciente a más antigua, para que en la primera página vea lo más nuevo

**Comment by AleToroY** [comment]
Danilo, según lo que hablamos hoy entonces estamos ok con este ajuste, digo para cerrarlo, me avisas para ajustar los tickets. Gracias!! @chapalele
