### ISSUE TITLE
(SB) desplegable de región y comuna, que la región esté primero y que dado esa elección se despliegue despues comuna. 

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#57]

**Comment by chapalele** [comment]
solución: publicar evento "formulario cargado" en JS

**Comment by AleToroY** [comment]
Hola Danilo, no entiendo tu comentario, ¿es algo interno tuyo o necesitas algo?

**Comment by chapalele** [comment]
perdona, es interno, voy marcar las notas para no confundir.  gracias

**Comment by AleToroY** [comment]
Danilo, según lo que hablamos hoy entonces estamos ok con este ajuste, digo para cerrarlo, me avisas para ajustar los tickets. Gracias!! @chapalele
