### ISSUE TITLE
(SB) Sacar del gráfico de denuncias y consultas las declaraciones de proveedores, porque se ve muy lleno y, por favor, que exista un gráfico aparte con las declaraciones de proveedores.

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#60]

**Comment by chapalele** [comment]
@AleToroY el par de gráficos está publicado en stage.
Adicionalmente, quité de la lista de gráficos de SB (en la configuración, no en el código) el gráfico de casos anuales por tipo
