### ISSUE TITLE
(SB) Que en los gráficos se vean fijos los números. Esto tengo toda la impresión que ya lo habíamos hecho. Al menos pillé un correo del 4 diciembre 2020, donde hablamos de dejarlos fijo al exportar. 

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#61]

**Comment by chapalele** [comment]
hasta ahora no tenemos una solución para dejar los valores en las columnas y al mismo tiempo el número de columnas variables.  
No cierro el ticket porque requiere más investigación.

**Comment by chapalele** [comment]
hecha la revisión, confirmo que el ajuste automático de columnas es la mejor solución disponible. Etiquetas en columnas variables no están disponibles.
