### ISSUE TITLE
(MP) 7.	Se señaló, para el expediente, que se haría alguna distinción respecto de quién intervino. No me quedó claro. No lo pude evidenciar en las pruebas usando distintos perfiles (sólo señala “la persona a cargo”). Favor comentar cómo funciona.

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#65]

**Comment by chapalele** [comment]
Este es un parámetro que se ajusta en la configuración de la empresa.  
si decide ocultar el nombre (es el caso de ministerio público), el registro indica "la persona a cargo del caso" o algo así
si decide publicar el nombre del responsabel, el registro indica "_nombre_ _apellido_ ingresa información..."

ver screenshot.

![Screen Shot 2021-06-02 at 2 41 16 PM](https://user-images.githubusercontent.com/168235/120535383-e810af00-c3b0-11eb-982a-bbfd8c0f5a8b.png)
