### ISSUE TITLE
(MP) 9.	En expediente se agregó posibilidad de subir archivo (se había consultado por si se requiriese enviarle algo al usuario no identificado). Entiendo que como quedó, es más bien para archivos entre la interfaz de quienes gestionen el caso. Confirmar criterio.

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#66]

**Comment by chapalele** [comment]
esto se regula con un parámetro que se define en la interfaz de administración: no hay nada que programar. sólo decidir cómo quiere que el sistema se comporte y definirlo así en los parámetros (ver screenshot)

![Screen Shot 2021-06-02 at 2 39 07 PM](https://user-images.githubusercontent.com/168235/120534911-602aa500-c3b0-11eb-9a80-fee8c6526743.png)
