### ISSUE TITLE
(MP)10.	En casos MALS lsnlvh83 y ldqteihv, aun habiendo ingresado RUN y teléfono de contacto, no lo registró o no muestra en expediente de gestores del caso; sí se ve en el expediente que ve el usuario. Revisar. Esto tb es importante. Además, ver si hay algún tema de formato (hice otro caso con RUN y guión y celular con +56 y esos sí aparecieron en los expedientes desde los gestores).

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#67]

**Comment by chapalele** [comment]
Los datos no fueron registrados, pero no es posible reproducir el problema con las versiones al día del sistema.
Los casos citados fueron ingresados el 17 de mayo, (hay 4 versiones y 9 cambios pedidos al sistema después de esa fecha).  
Sin más información, tengo que cerrar este tema.
