### ISSUE TITLE
(MP) 12.	Dejar lo de información y estadísticas al menos como lo mostrado en la otra versión o lo mostrado en la capacitación, para poder partir desde ahí.

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#68]

**Comment by chapalele** [comment]
No se puede tener todo: hay que elegir
como MP sólo usa denuncias y consultas podría volver a la versión 5 y tener todo lo de esa versión ¿pero todo lo que hemos sumado a la v6 para MP?
