### ISSUE TITLE
(MP) 13.	Se había pedido cambiar el nombre de la pestaña Usuarios por Responsables; sólo se cambió como nombre de la columna de la grilla, pero no en la pestaña.

### ISSUE THREAD

**Issue by AleToroY** [chapalele/integridad-corporativa-issues#69]

**Comment by chapalele** [comment]
marcado como "wontfix", porque en ese menu se entra a la lista de usuarios, no a la lista de responsables.

responsable: aquel que es "responsable" de un caso
usuarios registrados: todo aquel que entra a la plataforma con un nombre de usuario y contraseña, incluyendo usuarios con perfil de estadísticas y lectura.  por ejemplo: "miembros del comité de ética".

![Screen Shot 2021-06-02 at 2 35 23 PM](https://user-images.githubusercontent.com/168235/120534420-cd8a0600-c3af-11eb-8a47-2b6d71b923a7.png)
